/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAfiliadosRouteImport } from './routes/_authenticated/afiliados'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAnaliseLocalizacaoRouteImport } from './routes/_authenticated/analise-localizacao'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedDiscadorRouteImport } from './routes/_authenticated/discador'
import { Route as AuthenticatedEmailCcaRouteImport } from './routes/_authenticated/email-cca'
import { Route as AuthenticatedFluxosRouteImport } from './routes/_authenticated/fluxos'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedLeiloesRouteImport } from './routes/_authenticated/leiloes'
import { Route as AuthenticatedMidiasSociaisRouteImport } from './routes/_authenticated/midias-sociais'
import { Route as AuthenticatedSimuladorFinanciamentoRouteImport } from './routes/_authenticated/simulador-financiamento'
import { Route as AuthenticatedSpeedToLeadRouteImport } from './routes/_authenticated/speed-to-lead'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as Char91DotlovableOauthConsentChar93RouteImport } from './routes/[.lovable.oauth.consent]'
import { Route as AuthenticatedAdminParametrosRouteImport } from './routes/_authenticated/admin/parametros'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as ApiPublicStatusRouteImport } from './routes/api/public/status'
import { Route as ApiPublicHooksLeadsRouteImport } from './routes/api/public/hooks/leads'
import { Route as ApiPublicHooksN8nWebhookRouteImport } from './routes/api/public/hooks/n8n-webhook'
import { Route as ApiPublicHooksPropertiesRouteImport } from './routes/api/public/hooks/properties'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksWhatsappRouteImport } from './routes/api/public/hooks/whatsapp'
import { Route as ApiPublicJobsPropertyDiscoveryRouteImport } from './routes/api/public/jobs/property-discovery'
import { Route as ApiPublicJobsPropertyFeedsRouteImport } from './routes/api/public/jobs/property-feeds'
import { Route as ApiPublicOauthMetaRouteImport } from './routes/api/public/oauth/meta'
import { Route as ApiPublicVoiceBridgeRouteImport } from './routes/api/public/voice/bridge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAfiliadosRoute = AuthenticatedAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnaliseLocalizacaoRoute =
  AuthenticatedAnaliseLocalizacaoRouteImport.update({
    id: '/analise-localizacao',
    path: '/analise-localizacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiscadorRoute = AuthenticatedDiscadorRouteImport.update({
  id: '/discador',
  path: '/discador',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailCcaRoute = AuthenticatedEmailCcaRouteImport.update({
  id: '/email-cca',
  path: '/email-cca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFluxosRoute = AuthenticatedFluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeiloesRoute = AuthenticatedLeiloesRouteImport.update({
  id: '/leiloes',
  path: '/leiloes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMidiasSociaisRoute =
  AuthenticatedMidiasSociaisRouteImport.update({
    id: '/midias-sociais',
    path: '/midias-sociais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladorFinanciamentoRoute =
  AuthenticatedSimuladorFinanciamentoRouteImport.update({
    id: '/simulador-financiamento',
    path: '/simulador-financiamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpeedToLeadRoute =
  AuthenticatedSpeedToLeadRouteImport.update({
    id: '/speed-to-lead',
    path: '/speed-to-lead',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotlovableOauthConsentChar93Route =
  Char91DotlovableOauthConsentChar93RouteImport.update({
    id: '/[.lovable/oauth/consent]',
    path: '/[.lovable/oauth/consent]',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminParametrosRoute =
  AuthenticatedAdminParametrosRouteImport.update({
    id: '/admin/parametros',
    path: '/admin/parametros',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicStatusRoute = ApiPublicStatusRouteImport.update({
  id: '/api/public/status',
  path: '/api/public/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLeadsRoute = ApiPublicHooksLeadsRouteImport.update({
  id: '/api/public/hooks/leads',
  path: '/api/public/hooks/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksN8nWebhookRoute =
  ApiPublicHooksN8nWebhookRouteImport.update({
    id: '/api/public/hooks/n8n-webhook',
    path: '/api/public/hooks/n8n-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPropertiesRoute =
  ApiPublicHooksPropertiesRouteImport.update({
    id: '/api/public/hooks/properties',
    path: '/api/public/hooks/properties',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWhatsappRoute = ApiPublicHooksWhatsappRouteImport.update({
  id: '/api/public/hooks/whatsapp',
  path: '/api/public/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsPropertyDiscoveryRoute =
  ApiPublicJobsPropertyDiscoveryRouteImport.update({
    id: '/api/public/jobs/property-discovery',
    path: '/api/public/jobs/property-discovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPropertyFeedsRoute =
  ApiPublicJobsPropertyFeedsRouteImport.update({
    id: '/api/public/jobs/property-feeds',
    path: '/api/public/jobs/property-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthMetaRoute = ApiPublicOauthMetaRouteImport.update({
  id: '/api/public/oauth/meta',
  path: '/api/public/oauth/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceBridgeRoute = ApiPublicVoiceBridgeRouteImport.update({
  id: '/api/public/voice/bridge',
  path: '/api/public/voice/bridge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/analise-localizacao': typeof AuthenticatedAnaliseLocalizacaoRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/discador': typeof AuthenticatedDiscadorRoute
  '/email-cca': typeof AuthenticatedEmailCcaRoute
  '/fluxos': typeof AuthenticatedFluxosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/leiloes': typeof AuthenticatedLeiloesRoute
  '/midias-sociais': typeof AuthenticatedMidiasSociaisRoute
  '/simulador-financiamento': typeof AuthenticatedSimuladorFinanciamentoRoute
  '/speed-to-lead': typeof AuthenticatedSpeedToLeadRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/[.lovable/oauth/consent]': typeof Char91DotlovableOauthConsentChar93Route
  '/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/api/public/hooks/leads': typeof ApiPublicHooksLeadsRoute
  '/api/public/hooks/n8n-webhook': typeof ApiPublicHooksN8nWebhookRoute
  '/api/public/hooks/properties': typeof ApiPublicHooksPropertiesRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/jobs/property-discovery': typeof ApiPublicJobsPropertyDiscoveryRoute
  '/api/public/jobs/property-feeds': typeof ApiPublicJobsPropertyFeedsRoute
  '/api/public/oauth/meta': typeof ApiPublicOauthMetaRoute
  '/api/public/voice/bridge': typeof ApiPublicVoiceBridgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/analise-localizacao': typeof AuthenticatedAnaliseLocalizacaoRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/discador': typeof AuthenticatedDiscadorRoute
  '/email-cca': typeof AuthenticatedEmailCcaRoute
  '/fluxos': typeof AuthenticatedFluxosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/leiloes': typeof AuthenticatedLeiloesRoute
  '/midias-sociais': typeof AuthenticatedMidiasSociaisRoute
  '/simulador-financiamento': typeof AuthenticatedSimuladorFinanciamentoRoute
  '/speed-to-lead': typeof AuthenticatedSpeedToLeadRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/[.lovable/oauth/consent]': typeof Char91DotlovableOauthConsentChar93Route
  '/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/api/public/hooks/leads': typeof ApiPublicHooksLeadsRoute
  '/api/public/hooks/n8n-webhook': typeof ApiPublicHooksN8nWebhookRoute
  '/api/public/hooks/properties': typeof ApiPublicHooksPropertiesRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/jobs/property-discovery': typeof ApiPublicJobsPropertyDiscoveryRoute
  '/api/public/jobs/property-feeds': typeof ApiPublicJobsPropertyFeedsRoute
  '/api/public/oauth/meta': typeof ApiPublicOauthMetaRoute
  '/api/public/voice/bridge': typeof ApiPublicVoiceBridgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/afiliados': typeof AuthenticatedAfiliadosRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/analise-localizacao': typeof AuthenticatedAnaliseLocalizacaoRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/discador': typeof AuthenticatedDiscadorRoute
  '/_authenticated/email-cca': typeof AuthenticatedEmailCcaRoute
  '/_authenticated/fluxos': typeof AuthenticatedFluxosRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/leiloes': typeof AuthenticatedLeiloesRoute
  '/_authenticated/midias-sociais': typeof AuthenticatedMidiasSociaisRoute
  '/_authenticated/simulador-financiamento': typeof AuthenticatedSimuladorFinanciamentoRoute
  '/_authenticated/speed-to-lead': typeof AuthenticatedSpeedToLeadRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/[.lovable/oauth/consent]': typeof Char91DotlovableOauthConsentChar93Route
  '/_authenticated/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/api/public/hooks/leads': typeof ApiPublicHooksLeadsRoute
  '/api/public/hooks/n8n-webhook': typeof ApiPublicHooksN8nWebhookRoute
  '/api/public/hooks/properties': typeof ApiPublicHooksPropertiesRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/jobs/property-discovery': typeof ApiPublicJobsPropertyDiscoveryRoute
  '/api/public/jobs/property-feeds': typeof ApiPublicJobsPropertyFeedsRoute
  '/api/public/oauth/meta': typeof ApiPublicOauthMetaRoute
  '/api/public/voice/bridge': typeof ApiPublicVoiceBridgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/afiliados'
    | '/alertas'
    | '/analise-localizacao'
    | '/assinatura'
    | '/assistente'
    | '/atendimento'
    | '/buscar'
    | '/crm'
    | '/dashboard'
    | '/diagnostico'
    | '/discador'
    | '/email-cca'
    | '/fluxos'
    | '/integracoes'
    | '/leiloes'
    | '/midias-sociais'
    | '/simulador-financiamento'
    | '/speed-to-lead'
    | '/.mcp/invoke-tool/$tool'
    | '/[.lovable/oauth/consent]'
    | '/admin/parametros'
    | '/admin/usuarios'
    | '/settings/security'
    | '/api/public/status'
    | '/api/public/hooks/leads'
    | '/api/public/hooks/n8n-webhook'
    | '/api/public/hooks/properties'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/whatsapp'
    | '/api/public/jobs/property-discovery'
    | '/api/public/jobs/property-feeds'
    | '/api/public/oauth/meta'
    | '/api/public/voice/bridge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/afiliados'
    | '/alertas'
    | '/analise-localizacao'
    | '/assinatura'
    | '/assistente'
    | '/atendimento'
    | '/buscar'
    | '/crm'
    | '/dashboard'
    | '/diagnostico'
    | '/discador'
    | '/email-cca'
    | '/fluxos'
    | '/integracoes'
    | '/leiloes'
    | '/midias-sociais'
    | '/simulador-financiamento'
    | '/speed-to-lead'
    | '/.mcp/invoke-tool/$tool'
    | '/[.lovable/oauth/consent]'
    | '/admin/parametros'
    | '/admin/usuarios'
    | '/settings/security'
    | '/api/public/status'
    | '/api/public/hooks/leads'
    | '/api/public/hooks/n8n-webhook'
    | '/api/public/hooks/properties'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/whatsapp'
    | '/api/public/jobs/property-discovery'
    | '/api/public/jobs/property-feeds'
    | '/api/public/oauth/meta'
    | '/api/public/voice/bridge'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/afiliados'
    | '/_authenticated/alertas'
    | '/_authenticated/analise-localizacao'
    | '/_authenticated/assinatura'
    | '/_authenticated/assistente'
    | '/_authenticated/atendimento'
    | '/_authenticated/buscar'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostico'
    | '/_authenticated/discador'
    | '/_authenticated/email-cca'
    | '/_authenticated/fluxos'
    | '/_authenticated/integracoes'
    | '/_authenticated/leiloes'
    | '/_authenticated/midias-sociais'
    | '/_authenticated/simulador-financiamento'
    | '/_authenticated/speed-to-lead'
    | '/.mcp/invoke-tool/$tool'
    | '/[.lovable/oauth/consent]'
    | '/_authenticated/admin/parametros'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/settings/security'
    | '/api/public/status'
    | '/api/public/hooks/leads'
    | '/api/public/hooks/n8n-webhook'
    | '/api/public/hooks/properties'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/whatsapp'
    | '/api/public/jobs/property-discovery'
    | '/api/public/jobs/property-feeds'
    | '/api/public/oauth/meta'
    | '/api/public/voice/bridge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  Char91DotlovableOauthConsentChar93Route: typeof Char91DotlovableOauthConsentChar93Route
  ApiPublicStatusRoute: typeof ApiPublicStatusRoute
  ApiPublicHooksLeadsRoute: typeof ApiPublicHooksLeadsRoute
  ApiPublicHooksN8nWebhookRoute: typeof ApiPublicHooksN8nWebhookRoute
  ApiPublicHooksPropertiesRoute: typeof ApiPublicHooksPropertiesRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
  ApiPublicHooksWhatsappRoute: typeof ApiPublicHooksWhatsappRoute
  ApiPublicJobsPropertyDiscoveryRoute: typeof ApiPublicJobsPropertyDiscoveryRoute
  ApiPublicJobsPropertyFeedsRoute: typeof ApiPublicJobsPropertyFeedsRoute
  ApiPublicOauthMetaRoute: typeof ApiPublicOauthMetaRoute
  ApiPublicVoiceBridgeRoute: typeof ApiPublicVoiceBridgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/afiliados': {
      id: '/_authenticated/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AuthenticatedAfiliadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analise-localizacao': {
      id: '/_authenticated/analise-localizacao'
      path: '/analise-localizacao'
      fullPath: '/analise-localizacao'
      preLoaderRoute: typeof AuthenticatedAnaliseLocalizacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discador': {
      id: '/_authenticated/discador'
      path: '/discador'
      fullPath: '/discador'
      preLoaderRoute: typeof AuthenticatedDiscadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-cca': {
      id: '/_authenticated/email-cca'
      path: '/email-cca'
      fullPath: '/email-cca'
      preLoaderRoute: typeof AuthenticatedEmailCcaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fluxos': {
      id: '/_authenticated/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof AuthenticatedFluxosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leiloes': {
      id: '/_authenticated/leiloes'
      path: '/leiloes'
      fullPath: '/leiloes'
      preLoaderRoute: typeof AuthenticatedLeiloesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/midias-sociais': {
      id: '/_authenticated/midias-sociais'
      path: '/midias-sociais'
      fullPath: '/midias-sociais'
      preLoaderRoute: typeof AuthenticatedMidiasSociaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulador-financiamento': {
      id: '/_authenticated/simulador-financiamento'
      path: '/simulador-financiamento'
      fullPath: '/simulador-financiamento'
      preLoaderRoute: typeof AuthenticatedSimuladorFinanciamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/speed-to-lead': {
      id: '/_authenticated/speed-to-lead'
      path: '/speed-to-lead'
      fullPath: '/speed-to-lead'
      preLoaderRoute: typeof AuthenticatedSpeedToLeadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/[.lovable/oauth/consent]': {
      id: '/[.lovable/oauth/consent]'
      path: '/[.lovable/oauth/consent]'
      fullPath: '/[.lovable/oauth/consent]'
      preLoaderRoute: typeof Char91DotlovableOauthConsentChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/parametros': {
      id: '/_authenticated/admin/parametros'
      path: '/admin/parametros'
      fullPath: '/admin/parametros'
      preLoaderRoute: typeof AuthenticatedAdminParametrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/status': {
      id: '/api/public/status'
      path: '/api/public/status'
      fullPath: '/api/public/status'
      preLoaderRoute: typeof ApiPublicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/leads': {
      id: '/api/public/hooks/leads'
      path: '/api/public/hooks/leads'
      fullPath: '/api/public/hooks/leads'
      preLoaderRoute: typeof ApiPublicHooksLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/n8n-webhook': {
      id: '/api/public/hooks/n8n-webhook'
      path: '/api/public/hooks/n8n-webhook'
      fullPath: '/api/public/hooks/n8n-webhook'
      preLoaderRoute: typeof ApiPublicHooksN8nWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/properties': {
      id: '/api/public/hooks/properties'
      path: '/api/public/hooks/properties'
      fullPath: '/api/public/hooks/properties'
      preLoaderRoute: typeof ApiPublicHooksPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp': {
      id: '/api/public/hooks/whatsapp'
      path: '/api/public/hooks/whatsapp'
      fullPath: '/api/public/hooks/whatsapp'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/property-discovery': {
      id: '/api/public/jobs/property-discovery'
      path: '/api/public/jobs/property-discovery'
      fullPath: '/api/public/jobs/property-discovery'
      preLoaderRoute: typeof ApiPublicJobsPropertyDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/property-feeds': {
      id: '/api/public/jobs/property-feeds'
      path: '/api/public/jobs/property-feeds'
      fullPath: '/api/public/jobs/property-feeds'
      preLoaderRoute: typeof ApiPublicJobsPropertyFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta': {
      id: '/api/public/oauth/meta'
      path: '/api/public/oauth/meta'
      fullPath: '/api/public/oauth/meta'
      preLoaderRoute: typeof ApiPublicOauthMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/bridge': {
      id: '/api/public/voice/bridge'
      path: '/api/public/voice/bridge'
      fullPath: '/api/public/voice/bridge'
      preLoaderRoute: typeof ApiPublicVoiceBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAfiliadosRoute: typeof AuthenticatedAfiliadosRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAnaliseLocalizacaoRoute: typeof AuthenticatedAnaliseLocalizacaoRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedDiscadorRoute: typeof AuthenticatedDiscadorRoute
  AuthenticatedEmailCcaRoute: typeof AuthenticatedEmailCcaRoute
  AuthenticatedFluxosRoute: typeof AuthenticatedFluxosRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedLeiloesRoute: typeof AuthenticatedLeiloesRoute
  AuthenticatedMidiasSociaisRoute: typeof AuthenticatedMidiasSociaisRoute
  AuthenticatedSimuladorFinanciamentoRoute: typeof AuthenticatedSimuladorFinanciamentoRoute
  AuthenticatedSpeedToLeadRoute: typeof AuthenticatedSpeedToLeadRoute
  AuthenticatedAdminParametrosRoute: typeof AuthenticatedAdminParametrosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAfiliadosRoute: AuthenticatedAfiliadosRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAnaliseLocalizacaoRoute: AuthenticatedAnaliseLocalizacaoRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedDiscadorRoute: AuthenticatedDiscadorRoute,
  AuthenticatedEmailCcaRoute: AuthenticatedEmailCcaRoute,
  AuthenticatedFluxosRoute: AuthenticatedFluxosRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedLeiloesRoute: AuthenticatedLeiloesRoute,
  AuthenticatedMidiasSociaisRoute: AuthenticatedMidiasSociaisRoute,
  AuthenticatedSimuladorFinanciamentoRoute:
    AuthenticatedSimuladorFinanciamentoRoute,
  AuthenticatedSpeedToLeadRoute: AuthenticatedSpeedToLeadRoute,
  AuthenticatedAdminParametrosRoute: AuthenticatedAdminParametrosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  Char91DotlovableOauthConsentChar93Route:
    Char91DotlovableOauthConsentChar93Route,
  ApiPublicStatusRoute: ApiPublicStatusRoute,
  ApiPublicHooksLeadsRoute: ApiPublicHooksLeadsRoute,
  ApiPublicHooksN8nWebhookRoute: ApiPublicHooksN8nWebhookRoute,
  ApiPublicHooksPropertiesRoute: ApiPublicHooksPropertiesRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
  ApiPublicHooksWhatsappRoute: ApiPublicHooksWhatsappRoute,
  ApiPublicJobsPropertyDiscoveryRoute: ApiPublicJobsPropertyDiscoveryRoute,
  ApiPublicJobsPropertyFeedsRoute: ApiPublicJobsPropertyFeedsRoute,
  ApiPublicOauthMetaRoute: ApiPublicOauthMetaRoute,
  ApiPublicVoiceBridgeRoute: ApiPublicVoiceBridgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
