// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { PUBLIC_SUPABASE_PUBLISHABLE_KEY, PUBLIC_SUPABASE_URL } from "./public-config";

const ATTENDANCE_REALTIME_COMPAT_TABLES = new Set([
  "whatsapp_attendant_presence",
  "whatsapp_attendance_sessions",
]);

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function addAttendanceRealtimeCompatibility(client: ReturnType<typeof createSupabaseClientBase>) {
  const originalChannel = client.channel.bind(client);

  client.channel = ((...channelArgs: Parameters<typeof originalChannel>) => {
    const channel = originalChannel(...channelArgs);
    const originalOn = channel.on.bind(channel);

    channel.on = ((...onArgs: unknown[]) => {
      const event = onArgs[0];
      const filter = onArgs[1];
      if (
        event === "postgres_changes" &&
        filter &&
        typeof filter === "object" &&
        "table" in filter &&
        typeof filter.table === "string" &&
        ATTENDANCE_REALTIME_COMPAT_TABLES.has(filter.table)
      ) {
        onArgs[1] = { ...filter, table: "system_events" };
      }
      return Reflect.apply(originalOn, channel, onArgs);
    }) as typeof channel.on;

    return channel;
  }) as typeof client.channel;

  return client;
}

function createSupabaseClientBase() {
  if (!PUBLIC_SUPABASE_PUBLISHABLE_KEY) {
    throw new Error("MercadoImobi Supabase publishable key is not configured");
  }

  return createClient<Database>(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(PUBLIC_SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function createSupabaseClient() {
  return addAttendanceRealtimeCompatibility(createSupabaseClientBase());
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
